URL: http://www.baidu.com
RetingURL: https://azb.yzctid.com/renting/#/login
log:
    file_name: test.log
    backup: 5
    console_level: WARNING
    file_level: DEBUG
    pattern: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'